var ABMSG = {
	title:"About us",
	box1_1:"What are we doing？",
	box1_2:"We are fully committed to delivering the simplest",
	box1_3:"most engaging and creative way",
	box1_4:"to teach kids how to code",
	box1_5:" In this mission",
	box1_6:"we need your help",
	box1_7:"Feel free to send us",
	box1_8:"your honest feedback",
	memname1:"Jinshan Cai",
	memname2:"Zhijie Chen",
	memname3:"Qingfang Li",
	memname4:"Meimei Zheng",
	pa1_1:"Web front-end",
	pa1_2:"layout and dynamic effects",
	pa1_3:"blocks and workspace",
	pa2_1:"Game design",
	pa2_2:"Game level and fun design",
	pa2_3:"improve some functions",
	pa3_1:"Game development",
	pa3_2:"Integrate and define blocks",
	pa3_3:"API, game logic development",
	pa4_1:"Visual design",
	pa4_2:"UI design for Web pages ",
	pa4_3:"and games, animation",
	contact:"Contact us",
	name:"Your username",
	email:"Your E-mail address",
	message:"Your feedback",
	submitbtn:"Submit"
}